steps:
# Build and push the notes-app Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: Build-Notes-App
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/capstone-repo/notes-app:$COMMIT_SHA'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/capstone-repo/notes-app:latest'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push-Notes-App
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/capstone-repo/notes-app:$COMMIT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  id: Push-Notes-App-Latest
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/capstone-repo/notes-app:latest'

# Build and push the api-gateway Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: Build-API-Gateway
  args:
    - 'build'
    - '-f'
    - 'Dockerfile.gateway'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/capstone-repo/api-gateway:$COMMIT_SHA'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/capstone-repo/api-gateway:latest'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push-API-Gateway
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/capstone-repo/api-gateway:$COMMIT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  id: Push-API-Gateway-Latest
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/capstone-repo/api-gateway:latest'
  
logsBucket: 'gs://log_bucket_11'

options:
  logging: GCS_ONLY

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/capstone-repo/notes-app:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/capstone-repo/notes-app:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/capstone-repo/api-gateway:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/capstone-repo/api-gateway:latest'
